// <auto-generated />
using System;
using HospitalScheds.Serverce;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HospitalScheds.Serverce.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190905030119_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("HospitalScheds.Model.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatePerson");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("IsUse");

                    b.Property<string>("LoginName");

                    b.Property<string>("Pwd");

                    b.Property<string>("RoleName");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("UserInfolist");
                });
#pragma warning restore 612, 618
        }
    }
}
